//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMovies.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieEntities : DbContext
    {
        public MovieEntities()
            : base("name=MovieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryDetails> CategoryDetails { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<episode> episode { get; set; }
        public virtual DbSet<follow> follow { get; set; }
        public virtual DbSet<history> history { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<MovieRate> MovieRate { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<viewsByDate> viewsByDate { get; set; }
    }
}
