//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMovies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewsByDate
    {
        public int id { get; set; }
        public Nullable<int> movieId { get; set; }
        public Nullable<System.DateTime> day { get; set; }
        public Nullable<int> numView { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
